server:
  port: 8082
pid:
  id: 1
  name: pg
  age: 2
sheep:
  id: 1
  name: sx
  age: 2
dog:
  id: 1
  name: dn
  age: 2

--- # 分割线，下边是一个单独文档

person:
  name: zs
  age: 18
  birthDay: 2010/10/10 12:12:12
  like: true
  child:
    name: 李四
    age: 20
    birth-day: 2018/10/10 # birthDay可以写成birth-day
    text:
      - abc
      - def
      - |
        dogs:
          - name: 小黑
            age: 3
          - name: 小白
            age: 2
      - >
        测试换行
        测试换行
        测试换行
  dogs:
    - name: 小黑
      age: 3
    - name: 小白
      age: 2
  pigs:
    p1:
      name: 小蓝
      age: 3
    p2: { name: 小绿,age: 2 } #对象也可用{}表示