server:
  port: 8085

spring:
  datasource:
    # JDBC连接池
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: zt
    password: admin123

# 配置整合mybatis信息
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启驼峰命名规则
    map-underscore-to-camel-case: true