server:
  port: 8003

spring:

  # 提取到 bootstrap.yml
#  application:
#    name: sc-consul-provider
#  cloud:
#    consul:
#      host: localhost
#      port: 8500

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin123./
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cozz.common.entity
